application: Steel-cms
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  script: main.py
  
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /_ah/stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
builtins:
- remote_api: on